
#### reference  path
# transcriptome: /home/yx157/data/Index/refdata-cellranger-mm10-3.0.0 # gcb location
# dcc human genome
transcriptome: /datacommons/ydiaolab/genome_ref/refdata-gex-GRCh38-2020-A 
# transcriptome: /datacommons/ydiaolab/genome_ref/refdata-gex-mm10-2020-A
cellranger: /opt/apps/rhel7/cellranger-3.1.0/cellranger

CLUSTER_JSON: './cluster.json'
SAMPLES_JSON: './samples.json'





